# -*- coding: utf-8 -*-
# Copyright (C) 2023 Benjamin Thomas Schwertfeger
# GitHub: https://github.com/btschwertfeger
#

services:
  postgresql:
    image: postgres:13-bookworm
    environment:
      POSTGRES_USER: kraken-infinity-grid
      POSTGRES_PASSWORD: kraken-infinity-grid
      POSTGRES_DB: kraken-infinity-grid
      TZ: Europe/Berlin
    restart: on-failure
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kraken-infinity-grid"]
      interval: 10s
      retries: 5
    networks:
      - internal_network

  kraken-infinity-grid:
    build: .
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      # General settings
      KRAKEN_API_KEY: ${KRAKEN_API_KEY}
      KRAKEN_SECRET_KEY: ${KRAKEN_SECRET_KEY}
      KRAKEN_RUN_NAME: ${KRAKEN_RUN_NAME}
      KRAKEN_RUN_USERREF: ${KRAKEN_RUN_USERREF}
      KRAKEN_BOT_VERBOSE: false
      KRAKEN_DRY_RUN: false
      # Strategy settings
      KRAKEN_RUN_BASE_CURRENCY: ${KRAKEN_RUN_BASE_CURRENCY} # base currency
      KRAKEN_RUN_QUOTE_CURRENCY: ${KRAKEN_RUN_QUOTE_CURRENCY} # quote currency
      KRAKEN_RUN_AMOUNT_PER_GRID: ${KRAKEN_RUN_AMOUNT_PER_GRID} # quote size per trade
      KRAKEN_RUN_INTERVAL: ${KRAKEN_RUN_INTERVAL} # grid size
      KRAKEN_RUN_N_OPEN_BUY_ORDERS: ${KRAKEN_RUN_N_OPEN_BUY_ORDERS} # number of open buy orders
      KRAKEN_RUN_MAX_INVESTMENT: ${KRAKEN_RUN_MAX_INVESTMENT} # max investment in quote currency
      KRAKEN_RUN_STRATEGY: ${KRAKEN_RUN_STRATEGY} # strategy to use
      # Notification settings
      KRAKEN_RUN_TELEGRAM_TOKEN: ${KRAKEN_RUN_TELEGRAM_TOKEN}
      KRAKEN_RUN_TELEGRAM_CHAT_ID: ${KRAKEN_RUN_TELEGRAM_CHAT_ID}
      KRAKEN_RUN_EXCEPTION_TOKEN: ${KRAKEN_RUN_EXCEPTION_TOKEN}
      KRAKEN_RUN_EXCEPTION_CHAT_ID: ${KRAKEN_RUN_EXCEPTION_CHAT_ID}
      # Database settings
      KRAKEN_RUN_DB_USER: ${KRAKEN_RUN_DB_USER}
      KRAKEN_RUN_DB_NAME: ${KRAKEN_RUN_DB_NAME}
      KRAKEN_RUN_DB_PASSWORD: ${KRAKEN_RUN_DB_PASSWORD}
      KRAKEN_RUN_DB_HOST: ${KRAKEN_RUN_DB_HOST}
      KRAKEN_RUN_DB_PORT: ${KRAKEN_RUN_DB_PORT}
    restart: on-failure
    volumes:
      - gridbot-cache:/root/.cache/gridbot:rw
    networks:
      - internal_network

volumes:
  gridbot-cache:
    external: false
  postgres-data:
    external: false

networks:
  internal_network:
    driver: bridge
