# -*- coding: utf-8 -*-
# Copyright (C) 2025 Benjamin Thomas Schwertfeger
# GitHub: https://github.com/btschwertfeger
#
# Template workflow to build the project for a specific os and Python version,
# run the tests and upload the results to codecov.
#

name: CodeCov

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
      python-version:
        type: string
        required: true
    secrets:
      CODECOV_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  CodeCov:
    name: Coverage
    runs-on: ${{ inputs.os }}
    timeout-minutes: 10
    env:
      OS: ${{ inputs.os }}
      PYTHON: ${{ inputs.python-version }}
    environment:
      name: codecov
      url: https://app.codecov.io/github/btschwertfeger/kraken-infinity-grid/
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          disable-sudo: true
          egress-policy: audit
          allowed-endpoints: >
            api.codecov.io:443
            api.kraken.com:443
            api.github.com:443
            cli.codecov.io:443
            files.pythonhosted.org:443
            github.com:443
            objects.githubusercontent.com:443
            pypi.org:443
            storage.googleapis.com:443
            ws-auth.kraken.com:443
            ws.kraken.com:443

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install package
        run: |
          uv venv
          source .venv/bin/activate
          echo ${GITHUB_WORKSPACE}/.venv/bin >> $GITHUB_PATH
          uv pip install ".[test,dev]"

      - name: Generate coverage report
        run: pytest -vv --cov=${{ github.repository }} --cov-report=xml:coverage.xml tests

      - name: Export coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@1e68e06f1dbfde0e4cefc87efeba9e4643565303 # v5.1.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          flags: unittests
          name: codecov-umbrella
          verbose: true
