# -*- coding: utf-8 -*-
# Copyright (C) 2023 Benjamin Thomas Schwertfeger
# GitHub: https://github.com/btschwertfeger
#
# Template workflow to run the tests.
#

name: Test

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
      python-version:
        type: string
        required: true

permissions:
  contents: read

jobs:
  Test:
    name: Test ${{ inputs.os }} ${{ inputs.python-version }}
    runs-on: ${{ inputs.os }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          disable-sudo: true

      - name: Checkout repository
        uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb # v4.2.2

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@3fddbee7870211eda9047db10474808be43c71ec # v5.3.0
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install package (Linux or macOS)
        if: runner.os != 'Windows'
        run: |
          uv venv
          source .venv/bin/activate
          echo ${GITHUB_WORKSPACE}/.venv/bin >> $GITHUB_PATH
          uv pip install ".[test]"

      - name: Install package (Windows)
        if: runner.os == 'Windows'
        run: |
          uv venv
          .venv\Scripts\activate.ps1
          echo "$env:GITHUB_WORKSPACE\.venv\Scripts" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          uv pip install ".[test]"

      - name: Run the tests
        run: pytest -vv tests
