##    Checks the code logic, style and more
# -*- coding: utf-8 -*-
# Copyright (C) 2023 Benjamin Thomas Schwertfeger
# GitHub: https://github.com/btschwertfeger
#
# Workflow to apply pre-commit, build, test and upload the docker
# image. This job is only triggered during a release.

name: Release

on:
  release:
    types: [created]

concurrency:
  group: Release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ##    Checks the code logic, style and more
  ##
  Pre-Commit:
    uses: ./.github/workflows/_pre_commit.yaml

  ##    Builds the package for Python3.11
  ##
  Build:
    needs: [Pre-Commit]
    uses: ./.github/workflows/_build.yaml
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.11"]
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}

  ##    Build the latest Docker image
  ##
  Build-Docker-latest:
    needs: [Pre-Commit]
    uses: ./.github/workflows/_build_docker.yaml
    with:
      TAG: latest
    # secrets:
    #   DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    #   DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  ##    Build the tagged Docker image
  ##
  Build-Docker:
    needs: [Pre-Commit]
    uses: ./.github/workflows/_build_docker.yaml
    with:
      TAG: ${{ github.ref_name }}
    # secrets:
    #   DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    #   DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  ##    Run the unit and acceptance tests
  ##
  Test:
    needs: [Build]
    uses: ./.github/workflows/_test.yaml
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
